name = "glaze"
version = "1.0.0"
description = "🍩 Beautiful components for any website"

licences = ["Apache-2.0"]
repository = { type = "github", user = "daniellionel01", repo = "glaze", path = "glaze", tag-prefix = "glaze-" }

internal_modules = [
  "glaze/internal",
  "glaze/internal/*",
]

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"

[dev_dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
